#!/bin/bash

source "$(dirname "$0")/ft_util_inc_var"

if [ -z "$1" ]; then
    $S_LOG -s crit -d $S_NAME "\$1 is empty..."
    exit 1
else
    user_name="$1"
fi

if [ -z "$2" ]; then
    group_name="$user_name"
else
    group_name="$2"
fi

if [ "$(whoami)" != "root" ]; then
    $S_LOG -s crit -d $S_NAME "Please run as root! You are only \"$(whoami)\"."
    exit 2
fi

if [ ! $(getent passwd ${USER}) ]; then
    $S_LOG -s crit -d $S_NAME "Sorry \"$USER\" doesn't exist."
    exit 3
else
    user_home=$(eval echo "~${user_name}")
fi

if [ ! -e "${user_home}/.ssh/id_rsa.pub" ]; then

    [ ! -d "${user_home}/.ssh" ] && mkdir "${user_home}/.ssh"
    ssh-keygen -q -f "${user_home}/.ssh/id_rsa" -N "" -t rsa -C ${user_name}@$(hostname)
    [ ! -e "${user_home}/.ssh/authorized_keys" ] && touch "${user_home}/.ssh/authorized_keys"

    chown -R ${user_name}:${group_name} ${user_home}/.ssh
    chmod -R 600 ${user_home}/.ssh/
    chmod 700 ${user_home}/.ssh

    $S_LOG -s $? -d $S_NAME "Creation of SSH Keys in ${user_home}/.ssh/ EXIT_CODE=$?"

    if [ -e "${user_home}/.ssh/id_rsa.pub" ]; then
        pub_key=$(cat ${user_home}/.ssh/id_rsa.pub)
        id_key=$(cat ${user_home}/.ssh/id_rsa.pub | cut -f3 -d " ")

        echo
        echo "======================================"
        echo "==== ${user_home}/.ssh/id_rsa.pub"
        echo "======================================"
        echo
        echo "$pub_key"
        echo
        echo "======================================"
        echo "======================================"
        echo

        exit 0

    else
        $S_LOG -s err -d $S_NAME "SSH Keys in ${user_home}/.ssh/ could not be created!"
        exit 10
    fi

else
    $S_LOG -d $S_NAME "SSH Keys in ${user_home}/.ssh/ are present "
    exit 0
fi

# if [ ! -f "$ZBX_RUN/.ssh/id_rsa" ] || [ ! -f "$ZBX_RUN/.ssh/id_rsa.pub" ]
# then
#     ssh-keygen -q -t rsa -N '' -f $ZBX_RUN/.ssh/id_rsa <<<y 2>&1 >/dev/null
#     $S_LOG -d $S_NAME "Creating SSH keys in $ZBX_RUN/.ssh"
#     pub_key=$(cat $ZBX_RUN/.ssh/id_rsa.pub)
#     id_key=$(cat $ZBX_RUN/.ssh/id_rsa.pub | cut -f3 -d " ")
#     sed -i "/$id_key/d" /root/.ssh/authorized_keys
#     # echo $pub_key >> /root/.ssh/authorized_keys

#     touch $ZBX_RUN/.ssh/known_hosts
#     ssh-keygen -R localhost -f $ZBX_RUN/.ssh/known_hosts
#     ssh-keyscan -H localhost >> $ZBX_RUN/.ssh/known_hosts

#     chown -R zabbix:zabbix $ZBX_RUN/.ssh
#     chmod -R 600 $ZBX_RUN/.ssh/
#     chmod 700 $ZBX_RUN/.ssh
# fi
